#生产环境配置 原生jar包启动时 采用 --spring.profiles.active = prod
spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://47.113.185.5:3306/user_center
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  session: #session 一天失效
    timeout: 86400
